const allColors = ['maroon',
'silver',
'gray',
'white',
'red',
'purple',
'fuchsia',
'green',
'lime',
'olive',
'yellow',
'navy',
'blue',
'teal',
'aqua',
'orange',
'aliceblue',
'aquamarine',
'bisque',
'blueviolet',
'brown',
'burlywood',
'cadetblue',
'chartreuse',
'chocolate',
'coral',
'cornflowerblue',
'cornsilk',
'crimson',
'cyan',
'darkblue',
'darkcyan',
'darkgoldenrod',
'darkgreen',
'darkgrey',
'darkkhaki',
'darkmagenta',
'darkolivegreen',
'darkorange',
'darkorchid',
'darkred',
'darksalmon',
'darkseagreen',
'darkslateblue',
'darkslategrey',
'darkturquoise',
'darkviolet',
'deeppink',
'deepskyblue',
'dimgrey',
'dodgerblue',
'firebrick',
'forestgreen',
'gainsboro',
'gold',
'goldenrod',
'greenyellow',
'grey',
'honeydew',
'hotpink',
'indianred',
'indigo',
'khaki',
'magenta',
'mediumaquamarine',
'mediumblue',
'mediumorchid',
'mediumpurple',
'mediumseagreen',
'mediumslateblue',
'mediumspringgreen',
'mediumturquoise',
'mediumvioletred',
'midnightblue',
'mistyrose',
'orangered',
'orchid',
'palegoldenrod',
'palegreen',
'paleturquoise',
'palevioletred',
'saddlebrown',
'salmon',
'sandybrown',
'seagreen',
'seashell',
'sienna',
'skyblue',
'slateblue',
'slategray',
'snow',
'springgreen',
'steelblue',
'tan',
'tomato',
'turquoise',
'violet',
'wheat',
'yellowgreen'];


const colorContainer = document.querySelector("#color-container");
const colorDisplayer = document.querySelector("#color-display");
const colorNameDisplay = document.querySelector("#colorName-display");
for(color of allColors)
{
    const colorBox = document.createElement("div");
    colorBox.style.backgroundColor = color;
    colorBox.classList.add("colorBox");
    colorContainer.appendChild(colorBox);
    colorBox.addEventListener("click", function changeColor()
    {
        colorDisplayer.style.backgroundColor = colorBox.style.backgroundColor
        colorNameDisplay.innerText = colorDisplayer.style.backgroundColor;
    });
}


